import { KubeUser } from './types/kube/kube-user.type';

export const DATE_FORMAT = 'dd MMM yyyy';

// DEV USAGE ONLY
export const DEV_TOKEN =
  'eyJhbGciOiJSUzI1NiIsImtpZCI6IkYzNkI2NDUzQUQ1OEQwQTM0MTRBOTgxMDhGOEE3NkNBIiwidHlwIjoiYXQrand0In0.eyJuYmYiOjE3NDUwNDY0MDYsImV4cCI6MTc0NTA1MDAwNiwiaXNzIjoiaHR0cHM6Ly9oZWxwZGVza2xvZ2luLmt1YmUzNjUuY29tIiwiYXVkIjpbIkt1YmUuMzY1LkFwaSIsIkt1YmUuMzY1LkFkbWluLkFwaSJdLCJjbGllbnRfaWQiOiJLdWJlLjM2NS40ODUwN2QzZi0wZDcyLTQ1ZGQtOGIwZS00NmExOGFhZDE0MjYuVUkiLCJzdWIiOiJnbG9iYWxhZG1pbkBrdWJlMzY1LmNvbSIsImF1dGhfdGltZSI6MTc0NDc4ODI4MiwiaWRwIjoiRm9ybXMiLCJqdGkiOiJGMTExQTVDOENEQzFERDMxMzg4NkVEMEJGQ0RFRDBDRSIsInNpZCI6IjM3RDQ1MEFBREZFNzVCQUJCNTIzMjM2MEUyNkI1QjA1IiwiaWF0IjoxNzQ1MDI0MjUxLCJzY29wZSI6WyJvcGVuaWQiLCJwcm9maWxlIiwia3ViZS4zNjUuc2NvcGUiLCJvZmZsaW5lX2FjY2VzcyJdLCJhbXIiOlsiZXh0ZXJuYWwiXX0.ED8PKOQjRzPFsc9TJyugYADw7MJxvsVBxte5w-PpOsMtjRudq09NcJqk2Nna5tXRi8Cm6yQS1lWZ3Oqhmb1DPjfFY86gbnBWQTyDpC-_hKdXFbTYgJ6gFQIClyjTvQgy94bRH1I9pKsi6gL3B6vyHqzac79kByBEe0aNtE7OC8idfoyUvSTc-6umjOxCcAZGhyKAgSvwgsBgo-_Fkv7Tx89ePwFd_kWNsbJfb1DvLoZgrPbndu7_FfXS6Mp_RJW8piSTpVUDq1_aB6HGbJxDOwqfaqbQAsh6uKcTTrema_oaVpJPNM0pDGWeXmyR4BP0ByBrvaKWgP7o9M8uIM0qJA';
export const DEV_USER: KubeUser & Record<string, any> = {
  accountName: 'globaladmin@kube365.com',
  displayName: 'Global Administrator',
  email: 'globaladmin@kube365.com',
  formView: 'grid',
  managerAccountName: null,
  managerDisplayName: null,
  templateIndex: 0,
  theme: 'standard',
  sideMenuState: 'show',
  isAuthenticated: true,
  userProfileId: 1,
  userProfileFields: [
    {
      title: 'Company',
      code: 'Company',
      value: 'ISA Innovation',
    },
  ],
  timezone: '+800',
  languageCode: 'en-US',
  webUrl: 'https://helpdesk.kube365.com',
  apiUrl: 'https://helpdesk.kube365.com/api',
  graphapiUrl: 'https://helpdesk.kube365.com/graph.api',
  authenticationType: 'Forms',
  sessionId: '37D450AADFE75BABB5232360E26B5B05',
  allowUserOtp: false,
  scriptLoadTimeout: 8000,
  permissions: {
    delegationPermission: {
      delegateOwnTask: true,
      delegateTasksOnBehalfOfOtherApprovers: true,
      viewLink: true,
    },
    systemPermissions: [
      {
        systemPermissionCode: 'createformdesign',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'adminforms',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'formcategories',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'featuredforms',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'holidays',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'matrixes',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'masterlists',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'multilingualresources',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'notifications',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'quicklinks',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'tags',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'license',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'smtp',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'generalsettings',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'userdomains',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'usergroups',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'usergrouppermissions',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'userprofiles',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'userprofileproperties',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'auditlogs',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'systemlogs',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'appearancesettings',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'connectors',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'usagereport',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'userdashboard',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'apipermissions',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'assetscustomfiles',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'datasetting',
        canView: true,
        canManage: true,
        canExport: true,
      },
      {
        systemPermissionCode: 'datapatch',
        canView: true,
        canManage: true,
        canExport: false,
      },
    ],
  },
  clientTimezoneName: '(UTC+08:00) Kuala Lumpur, Singapore',
  tenant: {
    name: 'KUBE 365 Helpdesk',
    tenantGuid: 'bff9cc6c-b1e8-4c8d-a79a-b81b86b904ce',
    companyName: 'ISATEC Innovation Sdn Bhd',
    supportedTenants: [
      {
        name: 'KUBE 365 Support',
        companyName: 'ISATEC Innovation Sdn Bhd',
        tenantGuid: '97d32182-fe50-45f0-b7d6-f988ff1726d4',
        subDomainUrls: ['https://support.kube365.com'],
      },
    ],
  },
  adminTenant: {
    name: 'KUBE 365 Administration',
    companyName: 'KUBE 365 Global Administration',
    tenantGuid: 'f637d5f9-33e5-4d2f-aa7a-87422d08edfb',
    subDomainUrls: ['https://helpdeskadmin.kube365.com'],
  },
  isSystemAdmin: true,
  pagingSizeDefault: 10,
  pagingSizeList: [10, 20, 30, 50, 100],
  dropdownListSizeDefault: 50,
  maxDisplaySelectedItem: 3,
  systemDateFormat: 'dd MMM yyyy',
  systemDatetimeFormat: 'dd MMM yyyy HH:mm:ss',
  systemTimezone: '+0800',
  systemLanguage: 'en-US',
  availableLanguages: [
    {
      languageCode: 'en-US',
      isActive: true,
    },
  ],
  openNewTab: false,
  showDatatablePageLength: true,
  redirectToPageWithSideMenu: false,
  appearance: {
    published: [
      {
        settingType: 'custom',
        pageType: 'dashboard',
        htmlUrl:
          'https://helpdesk.kube365.com:443/api/contents/2/c-dashboard-html.html?t=1744959605860',
        scriptUrls: [
          'https://helpdesk.kube365.com:443/api/contents/2/c-dashboard-js.js?t=1744959605860',
        ],
      },
    ],
  },
  systemTheme: 'orange',
  actionableMessage: false,
  isCustomLogo: false,
  customLogoUpdated: 1725852768718,
  allowStageIntegrationTest: false,
  pdfTableSize: 500,
  datePickerMinYear: 1920,
  datePickerMaxYear: 2060,
  allowPushNotification: false,
  formDesignerFieldsSoftLimit: 100,
  formDesignerFieldsHardLimit: 250,
  formDesignerTableSoftLimit: 2,
  formDesignerTableHardLimit: 10,
  formDesignerTableColsSoftLimit: 12,
  formDesignerTableColsHardLimit: 15,
  allowReportCustomRendering: false,
  isCustomDashboard: false,
  isRestrictReapprovalAction: false,
  appVersion: '4.2.1.118',
  isEnterprise: true,
  allowPhysicalDiskStorage: true,
  activeEvents: ['keyup', 'click', 'scroll'],
};
